spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://appuser:appUser1@localhost:27017/onceaday?authSource=onceaday
      auto-index-creation: true
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

---

spring:
  config:
    activate:
      on-profile: prd
  data:
    mongodb:
      uri: mongodb://appuser:appUser1@localhost:27017/onceaday?authSource=onceaday
      auto-index-creation: true