spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    group:
      local:
        - "mongo-local"
        - "env-local"
      prd:
        - "mongo-prd"
        - "env-prd"
    include:
      - "env"
      - "mongo"